---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      requirements:
      commands:
        - python scripts/install_insiders_packages.py  # moved here safely
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
