---
coverage:
  status:
    project:
      default:
        target: 80%  # TODO: set to 100%
        threshold: 0%
    patch:
      default:
        target: 80%  # TODO: set to 100%
        threshold: 0%
